/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -p group.h:group.cpp -i types.h ../xml/group.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef GROUP_H_1323275408
#define GROUP_H_1323275408

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "types.h"

/*
 * Proxy class for interface fi.w1.wpa_supplicant1.Group
 */
class FiW1Wpa_supplicant1GroupInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "fi.w1.wpa_supplicant1.Group"; }

public:
    FiW1Wpa_supplicant1GroupInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~FiW1Wpa_supplicant1GroupInterface();

    Q_PROPERTY(QList<QDBusObjectPath> Members READ members)
    inline QList<QDBusObjectPath> members() const
    { return qvariant_cast< QList<QDBusObjectPath> >(property("Members")); }

    Q_PROPERTY(QVariantMap Properties READ properties WRITE setProperties)
    inline QVariantMap properties() const
    { return qvariant_cast< QVariantMap >(property("Properties")); }
    inline void setProperties(const QVariantMap &value)
    { setProperty("Properties", qVariantFromValue(value)); }

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void PeerDisconnected(const QDBusObjectPath &peer);
    void PeerJoined(const QDBusObjectPath &peer);
};

namespace fi {
  namespace w1 {
    namespace wpa_supplicant {
      typedef ::FiW1Wpa_supplicant1GroupInterface Group;
    }
  }
}
#endif
