/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -p p2pdevice.h:p2pdevice.cpp -i types.h ../xml/p2pdevice.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "p2pdevice.h"

/*
 * Implementation of interface class FiW1Wpa_supplicant1InterfaceP2PDeviceInterface
 */

FiW1Wpa_supplicant1InterfaceP2PDeviceInterface::FiW1Wpa_supplicant1InterfaceP2PDeviceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

FiW1Wpa_supplicant1InterfaceP2PDeviceInterface::~FiW1Wpa_supplicant1InterfaceP2PDeviceInterface()
{
}

