/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -p peer.h:peer.cpp -i types.h ../xml/peer.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef PEER_H_1323204472
#define PEER_H_1323204472

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "types.h"

/*
 * Proxy class for interface fi.w1.wpa_supplicant1.Peer
 */
class FiW1Wpa_supplicant1PeerInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "fi.w1.wpa_supplicant1.Peer"; }

public:
    FiW1Wpa_supplicant1PeerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~FiW1Wpa_supplicant1PeerInterface();

    Q_PROPERTY(QByteArray IEs READ iEs)
    inline QByteArray iEs() const
    { return qvariant_cast< QByteArray >(property("IEs")); }

    Q_PROPERTY(QVariantMap Properties READ properties)
    inline QVariantMap properties() const
    { return qvariant_cast< QVariantMap >(property("Properties")); }

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
};

namespace fi {
  namespace w1 {
    namespace wpa_supplicant {
      typedef ::FiW1Wpa_supplicant1PeerInterface Peer;
    }
  }
}
#endif
